In [25]:
# Lesson 1: Array 

In [1]:
import numpy as np

In [ ]:
## creation of array 
a = np.array([1,2,3])
b = np.array([[1,2],[3,4]])
c = np.array([[1],[2],[3],[4]])

print("1D :",a)
print("2D :\n",b)
print("3D :\n",c)

1D : [1 2 3]
2D :
 [[1 2]
 [3 4]]
3D :
 [[1]
 [2]
 [3]
 [4]]


In [9]:
## Use arange -- like python range()
arr = np.arange(0,10,2)  # start=0, stop<10, step=2
print("Arange :",arr)

Arange : [0 2 4 6 8]


In [14]:
arr = np.linspace(0,1,5) # 5 points between 0 to 1
print("linespace :",arr)

linespace : [0.   0.25 0.5  0.75 1.  ]


In [ ]:
## Special array
print("Zeros:\n",np.zeros((2,3)))   # 2 row 3 columns
print("Onces:\n",np.ones((2,3)))
print("Full:\n",np.full((2,3),7))   # 2 row 3 columns value=7
print("Eye (Identity):\n",np.eye(3))    # digonal values are 1


Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Onces:
 [[1. 1. 1.]
 [1. 1. 1.]]
Full:
 [[7 7 7]
 [7 7 7]]
Eye (Identity):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
arr = np.array([1.5,2.5], dtype=int)
print("dtype:",arr)
print("type of array:",type(arr))
print("Array dtype:",arr.dtype)

dtype: [1 2]
type of array: <class 'numpy.ndarray'>
Array dtype: int64


In [26]:
##  Lesson 2: Array Shape & Reshape

In [ ]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])
print("Array:\n",arr)
print("Shape:",arr.shape)   # (2, 3) → 2 rows, 3 columns

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)


In [31]:
## .reshape() for change shape
reshaped = arr.reshape(3, 2)
print("Reshaped (3x2):\n", reshaped)


# Total elements must remain the same!
# (2×3 = 3×2 = 6 elements)

Reshaped (3x2):
 [[1 2]
 [3 4]
 [5 6]]


In [ ]:
#  Use -1 to auto-infer shape

auto_shape = arr.reshape(-1,1) # Auto decide rows/cols
print("Reshape with -1\n",auto_shape)

## here we given -1,1 it gives 1 row and 1 column reshaped array

auto_shape = arr.reshape(-1,2)
print("Reshape with -1,2\n",auto_shape)

#  NumPy sees 6 elements, and you gave 2 columns → it calculates 3 rows automatically

Reshape with -1
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
Reshape with -1,2
 [[1 2]
 [3 4]
 [5 6]]


In [ ]:
# Flatten the Array – .ravel() vs .flatten()

# .flatten()

# Converts any shape array to a 1D array
# Returns a new copy of the data (independent of original)
# Example 1
a = np.array([[10,20],[30,40]])
print("Flatten():",a.flatten())  # Returns a copy

# Example 2
b = np.array([[1, 2], [3, 4]])

flat = b.flatten()
print(flat)  # [1 2 3 4]

flat[0] = 100
print("Original b:\n", b)  # Original unchanged

print("Changed:\n",flat)


Flatten(): [10 20 30 40]
[1 2 3 4]
Original b:
 [[1 2]
 [3 4]]
Changed:
 [100   2   3   4]


In [44]:
# Also flattens the array to 1D
# But returns a view, not a copy → changes affect the original

b = np.array([[1, 2], [3, 4]])

r = b.ravel()
r[0] = 100
print("Original b after ravel change:\n", b)


Original b after ravel change:
 [[100   2]
 [  3   4]]


In [40]:
# Transpose with .T

print("Original:\n",arr)
print("Transpose:\n",arr.T)

Original:
 [[1 2 3]
 [4 5 6]]
Transpose:
 [[1 4]
 [2 5]
 [3 6]]


In [47]:
# Lesson 3: Indexing, Slicing & Masking

import numpy as np

a = np.array([10,20,30,40,50])
print("a[0]:",a[0])
print("a[-1]:",a[-1])

a[0]: 10
a[-1]: 50


In [ ]:
b = np.array([[1,2,3],[4,5,6]])

print("b[0,1]",b[0,1])          # index+1 = row,index+1 = column
print("n[1][2]:",b[1][2])       

b[0,1] 2
n[1][2]: 6


In [ ]:
# Slicingd
# 1D array

print(a[1:4])     # [20 30 40]  # not include 4th index
print(a[:3])      # [10 20 30]  # assume starting = 0
print(a[::2])     # [10 30 50] (step=2) assume star = 0, end = len


[20 30 40]
[10 20 30]
[10 30 50]


In [ ]:
# 2D array Slicing
# array[row_start:row_end, col_start:col_end]

print(b[:, 1])    # [2 5] → all rows, column index 1
print(b[1, :])    # [4 5 6] → row index 1, all columns
print(b[0:2, 1:3])# submatrix


[2 5]
[4 5 6]
[[2 3]
 [5 6]]


In [ ]:
# Boolean Indexing (Filtering with Conditions)

arr = np.array([10,15,20,25,30])
print(arr>20)   # return boolean
print(arr[arr>20])  # return values

[False False False  True  True]
[25 30]


In [52]:
#  Conditional Replacement

arr[arr>20] = 100
print(arr)

[ 10  15  20 100 100]


In [53]:
# Fancy Indexing (Give a list of indexes)

a = np.array([5,10,15,20,25])
print(a[[1,3]])

[10 20]


In [55]:
#  Lesson 4: NumPy Arithmetic & Broadcasting
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print("Add:",a+b)
print("Substraction:",a-b)
print("Multiplication:",a*b)
print("Divide:",b/a)

Add: [5 7 9]
Substraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Divide: [4.  2.5 2. ]


In [ ]:
'''2. Broadcasting (Different Shapes)
Broadcasting means NumPy can stretch smaller arrays to match bigger ones without copying data.

 Simple Rule:
Smaller array shape is matched from the right side.'''

# 1: Add scalar to array

a = np.array([1,2,3])
print(a+10)     # here +10 is stretched → [10, 10, 10]


[11 12 13]


In [58]:
# 2: Add 1D row to 2D matrix (broadcast column-wise)

A = np.array([[1,2,3],[4,5,6]])
B = np.array([10,20,30])
print(A + B)

[[11 22 33]
 [14 25 36]]


In [59]:
# 3: Add column to 2D matrix (broadcast row-wise)

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[10],
              [20]])

print(A + B)


[[11 12 13]
 [24 25 26]]


In [60]:
# 3. Comparison Operator

a = np.array([1,2,3,4])
print(a>4)
print(a==3)


[False False False False]
[False False  True False]


In [ ]:
# 4. Math Functions (Element-wise)

a = np.array([1, 4, 9])

print("sqrt:", np.sqrt(a))       
print("exp:", np.exp(a))          
print("log:", np.log(a))          



sqrt: [1. 2. 3.]
exp: [2.71828183e+00 5.45981500e+01 8.10308393e+03]
log: [0.         1.38629436 2.19722458]


In [62]:
# 5. Aggregate Functions

a = np.array([[1, 2, 3],
              [4, 5, 6]])

print("Sum all:", np.sum(a))                 # 21
print("Sum row-wise:", np.sum(a, axis=1))    # [6, 15]
print("Sum col-wise:", np.sum(a, axis=0))    # [5, 7, 9]


Sum all: 21
Sum row-wise: [ 6 15]
Sum col-wise: [5 7 9]


In [63]:
# Lesson 5: Descriptive Statistics in NumPy

import numpy as np

a = np.array([1, 2, 3, 4, 5])
print("Mean:", np.mean(a))  # Output: 3.0

print("Median:", np.median(a))  # Output: 3.0

print("Std Dev:", np.std(a))  # Output: ~1.41

print("Variance:", np.var(a))  # Output: ~2.0

print("Min:", np.min(a))      # 1
print("Max:", np.max(a))      # 5


Mean: 3.0
Median: 3.0
Std Dev: 1.4142135623730951
Variance: 2.0
Min: 1
Max: 5


In [64]:
#  6. Index of Min/Max — np.argmin() & np.argmax()
print("Argmin:", np.argmin(a))  # Index of smallest element → 0
print("Argmax:", np.argmax(a))  # Index of largest element → 4


Argmin: 0
Argmax: 4


In [65]:
# 7. Axis-wise Stats for 2D Arrays
b = np.array([[1, 2, 3],
              [4, 5, 6]])

print("Mean (row-wise):", np.mean(b, axis=1))  # [2.0, 5.0]
print("Mean (col-wise):", np.mean(b, axis=0))  # [2.5, 3.5, 4.5]


Mean (row-wise): [2. 5.]
Mean (col-wise): [2.5 3.5 4.5]


In [67]:
# Lesson 6: NumPy Random Module

# 1. Random Integers — np.random.randint()
import numpy as np

# Random integers between 1 and 10 (excluding 10)
arr = np.random.randint(1, 10, size=(2, 3))
print("Random Integers:\n", arr)


Random Integers:
 [[8 6 7]
 [9 3 3]]


In [69]:
# 2. Random Floats — np.random.rand() & np.random.randn()

print("rand():", np.random.rand(2, 2))   # 0 to 1, uniform distribution
print("randn():", np.random.randn(2, 2)) # mean=0, std=1, normal distribution


rand(): [[0.25597262 0.54578009]
 [0.30705459 0.01977755]]
randn(): [[0.82918073 0.05729263]
 [1.14714796 0.01205908]]


In [ ]:
# 3. Seeding — np.random.seed()
# Use this to get same results every time

np.random.seed(42)
print(np.random.randint(1, 100, 5))


[52 93 15 72 61]


In [75]:
# 4. Shuffle Data — np.random.shuffle()
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print("Shuffled:", arr)


Shuffled: [5 4 1 2 3]


In [77]:
# 5. Random Choice — np.random.choice()

choices = np.random.choice([10, 20, 30, 40], size=3, replace=False)
print("Random choice:", choices)


Random choice: [40 30 10]


In [78]:
# Lesson 7: Boolean Masking in NumPy

# 1. Create a Condition-Based Mask
import numpy as np

arr = np.array([10, 15, 20, 25, 30])
mask = arr > 20
print("Mask:", mask)  # [False False False  True  True]


Mask: [False False False  True  True]


In [80]:
# 2. Use Mask to Filter Data
filtered = arr[mask]
print("Filtered:", filtered)  # [25 30]
# or
print("Inline filter:", arr[arr > 20])  # [25 30]



Filtered: [25 30]
Inline filter: [25 30]


In [81]:
# 3. Logical Operations

a = np.array([10, 20, 30, 40, 50])

print("a > 20:", a > 20)
print("a < 50:", a < 50)
print("(a > 20) & (a < 50):", (a > 20) & (a < 50))  # AND
print("(a < 20) | (a > 40):", (a < 20) | (a > 40))  # OR


a > 20: [False False  True  True  True]
a < 50: [ True  True  True  True False]
(a > 20) & (a < 50): [False False  True  True False]
(a < 20) | (a > 40): [ True False False False  True]


In [ ]:
#  4. Conditional Update (Vectorized if)

a[a > 25] = 100
print("Updated a:", a)
# No loops needed! It directly updates where condition is True


Updated a: [ 10  20 100 100 100]


In [ ]:
# 5. np.where() for if-else

a = np.array([10, 20, 30, 40, 50])

result = np.where(a > 25, "High", "Low")
print(result)               # ['Low' 'Low' 'High' 'High' 'High']


['Low' 'Low' 'High' 'High' 'High']


In [84]:
# 6. np.any() and np.all()
a = np.array([1, 2, 3, 4, 5])

print("Any > 3?", np.any(a > 3))    # True
print("All > 0?", np.all(a > 0))    # True
print("All > 3?", np.all(a > 3))    # False


Any > 3? True
All > 0? True
All > 3? False


In [1]:
# Lesson 8: Reshape, Stack, Split

# 1. Reshape Review
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
reshaped = a.reshape(2, 3)
print("Reshaped:\n", reshaped)


Reshaped:
 [[1 2 3]
 [4 5 6]]


In [2]:
# Stacking Arrays
# 2. Vertical Stacking — np.vstack()

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

v = np.vstack((a, b))
print("vstack:\n", v)


vstack:
 [[1 2 3]
 [4 5 6]]


In [3]:
# 3. Horizontal Stacking — np.hstack()

a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])

h = np.hstack((a,b))
print("hstack:\n",h)

hstack:
 [[1 4]
 [2 5]
 [3 6]]


In [ ]:
# 4. Column Stack — np.column_stack()

x = np.array([10,20,30])
y = np.array([1,2,3])
print("Column Stack:\n",np.column_stack((x,y)))
# Converts 1D arrays into columns of a 2D array

Column Stack:
 [[10  1]
 [20  2]
 [30  3]]


In [ ]:
# Splitting Arrays

a = np.array([[1,2,3,4],
              [5,6,7,8]])
left,right = np.hsplit(a,2)
print("Left:\n",left)
print("Right:\n",right)

In [5]:
# 6. np.vsplit() — Vertical Split

a = np.array([[1, 2],
              [3, 4],
              [5, 6],
              [7, 8]])

top, bottom = np.vsplit(a, 2)  # Split into 2 rows
print("Top:\n", top)
print("Bottom:\n", bottom)


Top:
 [[1 2]
 [3 4]]
Bottom:
 [[5 6]
 [7 8]]


In [ ]:
# Lesson 9: Matrix Operations

#  1. Matrix Multiplication — np.dot() / @

import numpy as np

A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

dot1 = np.dot(A, B)  # Method 1      (m × n) × (n × p) → (m × p)  row x column
dot2 = A @ B         # Method 2 (Python 3.5+)

print("Dot Product:\n", dot1)


Dot Product:
 [[19 22]
 [43 50]]


In [7]:
# 2. Element-wise Multiplication — *

print("Element-wise:\n", A * B)


Element-wise:
 [[ 5 12]
 [21 32]]


In [ ]:
# 3. Transpose — .T
print("Transpose of A:\n", A.T)     # Flips rows & columns.

Transpose of A:
 [[1 3]
 [2 4]]


In [9]:
# 4. Determinant — np.linalg.det()
det = np.linalg.det(A)
print("Determinant of A:", det)


Determinant of A: -2.0000000000000004


In [10]:
# 5. Inverse — np.linalg.inv()
inv_A = np.linalg.inv(A)
print("Inverse of A:\n", inv_A)


Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [11]:
# 6. Identity Matrix — np.eye()
I = np.eye(3)  # 3x3 Identity
print("Identity:\n", I)


Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
# Lesson 10: Statistics Operations

# Mean — np.mean()

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print("Mean:", np.mean(arr))  # (1+2+3+4+5) / 5 = 3.0


Mean: 3.0


In [16]:
# Median — np.median()

print("Median:", np.median(arr))  # Middle value after sorting
print("Standard Deviation:", np.std(arr))
print("Variance:", np.var(arr))
print("Min:", np.min(arr))
print("Max:", np.max(arr))


Median: 3.0
Standard Deviation: 1.4142135623730951
Variance: 2.0
Min: 1
Max: 5


In [ ]:
# Percentiles — np.percentile()

data = np.array([7, 8, 5, 6, 3, 4, 9])

print("25th percentile:", np.percentile(data, 25))
print("50th percentile (median):", np.percentile(data, 50))
print("75th percentile:", np.percentile(data, 75))

25th percentile: 4.5
50th percentile (median): 6.0
75th percentile: 7.5


In [17]:
#  Lesson 11: NumPy Random Functions

# np.random.randint() — Random Integers

import numpy as np

# Integers between 1 (inclusive) and 10 (exclusive)
ints = np.random.randint(1, 10, size=(2, 3))
print("Random Integers:\n", ints)


Random Integers:
 [[5 9 7]
 [1 4 3]]
